---
title: "Tests of Normality"
author: "coop711"
date: "2015년 3월 9일"
output: html_document
---

BMI data revisited
------------------

- rn96 자료 읽어들이기

```{r}
rn96<-read.table("rn96.txt",header=T,sep="")
rn96
BMI<-round(rn96$weight/(rn96$height/100)^2,digits=1)
BMI
cbind(rn96,BMI)
data.frame(rn96,BMI)
```

- 정규분포 여부를 검증하는 nortest 패키지 설치

```{r}
install.packages("nortest", )
library(nortest)
```

Problems with hist()
====================

Quetelet's Chest Circumference Data
------------------------------------

- Data Construction

```{r}
chest<-33:48
freq<-c(3,18,81,185,420,749,1073,1079,934,658,370,92,50,21,4,1)
sum(freq)
```

- To create a data frame
```{r}
quetelet.chest<-data.frame(chest,freq)

```

- 5378 soldiers's chest circumferences were recorded. We should remember that the actual measuremens were rounded to the nearest integers. To draw 


You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
